server:
  port: 80

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/config.xml

logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:h2:file:~\database
    username: V2RayPanel
    password: b9ebd154-508c-40f9-ab2c-16f1996fe793
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
      path: /database
      settings:
        web-allow-others: false
  jackson:
    default-property-inclusion: non_null
